parking-lot:
  spots:
    total: 25
    motorcycle: 5
    compact-car: 10
    regular-car: 10
    min-space-for-van: 3

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: master
    password: master
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
