parking-lot:
  spaces:
    total: 25
    motorcycle: 5
    car-van: 20
    # There is no information for motorcycle parking lot so I will suppose that we have 5 free spaces

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: master
    password: master
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
